"""Code first migration based on existing models

Revision ID: f6e6c9eebc4b
Revises: 
Create Date: 2024-01-24 23:52:42.138563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e6c9eebc4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('efficiency', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=10), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('first_registration_date', sa.Date(), nullable=False),
    sa.Column('production_year', sa.String(length=4), nullable=False),
    sa.Column('mileage', sa.String(length=7), nullable=False),
    sa.Column('fuel_consumption', sa.String(length=5), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_type.id'], ),
    sa.ForeignKeyConstraint(['vehicle_status_id'], ['vehicle_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration'),
    sa.UniqueConstraint('vin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('vehicle_status')
    op.drop_table('fuel_type')
    # ### end Alembic commands ###
