version: '3.8'


services:
  # ===================================================================================
  # API GATEWAY MAIN DATABASE
  # ===================================================================================
  mysql_api_gateway:
    image: mysql:latest
    volumes:
      - mysql_api_gateway:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - 3307
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - flota-network

  # ===================================================================================
  # API GATEWAY TEST DATABASE
  # ===================================================================================
  mysql_test_api_gateway:
    image: mysql:latest
    volumes:
      - mysql_test_api_gateway:/var/lib/mysql

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    expose:
      - 3308
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - flota-network

  # ===================================================================================
  # CARS MAIN DATABASE
  # ===================================================================================
  mysql_cars:
    image: mysql:latest
    volumes:
      - mysql_cars:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3309
    ports:
      - '3309:3309'
    expose:
      - 3309
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - flota-network

  # ===================================================================================
  # CARS TEST DATABASE
  # ===================================================================================
  mysql_test_cars:
    image: mysql:latest
    volumes:
      - mysql_test_cars:/var/lib/mysql

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3310
    ports:
      - '3310:3310'
    expose:
      - 3310
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - flota-network

  # ===================================================================================
  # CARS SERVICE
  # ===================================================================================
  cars:
    build:
      context: ./cars
      dockerfile: Dockerfile

    command: gunicorn --bind 0.0.0.0:8001 --workers 6 'app.create_app:main()' --reload
    volumes:
      - ./cars:/webapp

    depends_on:
      mysql_cars:
        condition: service_healthy
      mysql_test_cars:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      flota-network:
        aliases:
          - cars-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

    command: gunicorn --bind 0.0.0.0:8000 --workers 6 'app.create_app:main()' --reload

    volumes:
      - ./api-gateway:/webapp
    depends_on:
      mysql_api_gateway:
        condition: service_healthy
      mysql_test_api_gateway:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      flota-network:
        aliases:
          - api-gateway-service

  nginx:
    image: nginx:latest
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - flota-network
    depends_on:
      - api-gateway


volumes:
  mysql_api_gateway:
  mysql_test_api_gateway:
  mysql_cars:
  mysql_test_cars:

networks:
  flota-network:
